### ISSUE TITLE
voice conversion did no effect on ubuntu 12.04

### ISSUE THREAD

**Issue by gqyan** [ShuhuaGao/vchsm#1]
Great thanks for this project, I am doing some study on voice conversion recently.
I complied this project successfully on ubuntu 12.04(64 bit,gcc version 4.9.6), and converted the wav file under test folder. However, even using the model file(Model.dat) you provided, there is no difference between source file and converted file (by my ear).  Is there any important thing I missed?  Please advise, thanks!

**Comment by ShuhuaGao** [comment]
Hi, gqyan, thanks for your feedback.
Actually, I am not familiar with the underlying algorithm. This is just a FYP project, which targets at the implementation of this algorithm based on a MATLAB version provided by the original author, Dr. Daniel Erro Eslava. For technical details, you may refer to the [PhD thesis](http://www.lsi.upc.edu/~nlp/papers/phd_daniel_erro.pdf). 
In our own tests, the conversion performance is not stable. For some source speaker and target speakers, the performance is much better than others. This algorithm is indeed a little old. The main advantage is that it can be implemented on even a mobile platform with an acceptable efficiency as a standalone application (we have developed one on iOS). It seems that with our supervisor as the source speaker and Prime Lee Hsien Loong  as the target speaker the conversion effect is quite satisfactory. 
Therefore, all I can tell you is that you may try other audio sources. For example, you may first prepare a text material to be read; then record your own voice and your friend's voice for the same text. After that, you can train the model and conduct further conversions. 
Besides, as I mentioned above, this algorithm is a little old (2008). If you are not limited to a mobile platform, you can try other advanced voice conversion algorithms, mainly based on deep learning, like [WaveNet](https://deepmind.com/blog/wavenet-generative-model-raw-audio/) developed by DeepMind.

**Comment by ShuhuaGao** [comment]
@gqyan  Besides, there are only two tunable parameters in our training interface: `numTrainSamples` and `m`. Usually, the more training samples, the better. However, in our test, 10 to 15 samples are usually enough (that's why this algorithm is efficient, taking about 35 seconds for training on iOS). For `m`, number of Gaussian components, you may play with that.

**Comment by gqyan** [comment]
thanks for your advise. I will create more training samples first.
