### ISSUE TITLE
Problems with training datasets

### ISSUE THREAD

**Issue by ThomasXu18** [ShuhuaGao/vchsm#2]
What are the requirements for training data? Must be parallel data?

**Comment by ShuhuaGao** [comment]
Hi, I have emphasized the data requirements in README.MD. Specifically, 

> Requirements of input audios:
Mono WAV, i.e., a single channel;
16 bits per sample;
16kHz sampling frequency.

**Comment by ThomasXu18** [comment]
Thank you for your reply!
I have noticed this. My question is whether the source speaker and target speaker need to say the same thing.

**Comment by ShuhuaGao** [comment]
Yes, they should say the some thing. I don't know whether it works if they speak different words. I didn't try that. But you may try 😀.
By the way, I have reorganized the code files. You may would like to pull/download the latest version.

**Comment by ThomasXu18** [comment]
👍
I will try it.

**Comment by ThomasXu18** [comment]
@ShuhuaGao  I heard that you have already developed an APP， where can i download your app ?
Can you speak Chinese？😀

**Comment by ShuhuaGao** [comment]
Yes, I speak Chinese.

About the iOS APP, it is just a prototype for a FYP project instead of a product. Sorry, you cannot get it 😀.  After all, it it just a GUI interface, and you can develop your own easily.

**Comment by ThomasXu18** [comment]
谢谢~  😀
最近也有计划在开发一款变声App。

close this issue
