### ISSUE TITLE
long time in [2]MFCC

### ISSUE THREAD

**Issue by LeandroMonteiro2018** [ShuhuaGao/vchsm#3]
First, thanks for sharing this implementation 😄. I utilized the project file in Visual Studio, and I enabled openmp in Language, but when I execute the program, it uses a high level of the CPU, but the time remains slow. I'm making tests on a Intel Core i7 CPU with 8gb RAM. Pardon me if I misunderstood something.

**Comment by ShuhuaGao** [comment]
Hi, did you run the test with the provided audio samples?
If in Visual Studio, do make sure that you have chosen the **Release** instead of Debug mode.  If you work in Debug mode, it will be very, very slow.

**Comment by LeandroMonteiro2018** [comment]
Yes, I used the audio samples provided. And by changing from Debug mode to Release mode, it worked 😄 . Thank you for answering this issue, really thanks. Sorry for my lack of skill 😅. Since it worked, I will close this issue soon.
