### ISSUE TITLE
感觉效果不太好。。。

### ISSUE THREAD

**Issue by WeiLi233** [ShuhuaGao/vchsm#4]
Hi, 作者你好，最近我在调研voice conversion的算法和实现，难得看到一个纯C++的实现，我按照样例测试了下，除了路径配置和Gauss component number之外，没有改其他的参数，demo的效果感觉并不好…我又尝试用voice conversion challenge 2018的公开数据做了一下平行语料的实验，用81段语音测试了下男转女的效果，感觉还是很不好，是我的复现中疏漏了什么参数的配置吗？

**Comment by ShuhuaGao** [comment]
这算法是多年前提出的了，与现在的基于Deep learning的应该没有可比性。我们采用它，仅是因为它的计算量很小，训练过程也可以在手机上较短时间内完成。具体到效果，离当前在大量计算资源下的state of art应该差很多了，你可以看到在论文中我们也提到了这点，仅是与一些基础的baseline做了比较。

如果你想拿它来开发APP用的话，我个人测试，当B有意模仿A的说话，比如语气和语速等，然后再经过转换，效果就会好得多。

**Comment by WeiLi233** [comment]
> 这算法是多年前提出的了，与现在的基于Deep learning的应该没有可比性。我们采用它，仅是因为它的计算量很小，训练过程也可以在手机上较短时间内完成。具体到效果，离当前在大量计算资源下的state of art应该差很多了，你可以看到在论文中我们也提到了这点，仅是与一些基础的baseline做了比较。
> 
> 如果你想拿它来开发APP用的话，我个人测试，当B有意模仿A的说话，比如语气和语速等，然后再经过转换，效果就会好得多。

Thanks a lot
